/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPLimitRouterCallback,
  IPLimitRouterCallbackInterface,
} from "../../../../../../@pendle/core-v2/contracts/interfaces/IPLimitRouter.sol/IPLimitRouterCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "actualMaking",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "actualTaking",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalFee",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "limitRouterCallback",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPLimitRouterCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IPLimitRouterCallbackInterface {
    return new Interface(_abi) as IPLimitRouterCallbackInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPLimitRouterCallback {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPLimitRouterCallback;
  }
}
