/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as v19Core from "./v1.9-core";
export type { v19Core };
import type * as v19Periphery from "./v1.9-periphery";
export type { v19Periphery };
