/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IPPYLpOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getLpToAssetRate"
      | "getLpToSyRate"
      | "getOracleState"
      | "getPtToAssetRate"
      | "getPtToSyRate"
      | "getYtToAssetRate"
      | "getYtToSyRate"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SetBlockCycleNumerator"): EventFragment;

  encodeFunctionData(
    functionFragment: "getLpToAssetRate",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLpToSyRate",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOracleState",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPtToAssetRate",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPtToSyRate",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getYtToAssetRate",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getYtToSyRate",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getLpToAssetRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLpToSyRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOracleState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPtToAssetRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPtToSyRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getYtToAssetRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getYtToSyRate",
    data: BytesLike
  ): Result;
}

export namespace SetBlockCycleNumeratorEvent {
  export type InputTuple = [newBlockCycleNumerator: BigNumberish];
  export type OutputTuple = [newBlockCycleNumerator: bigint];
  export interface OutputObject {
    newBlockCycleNumerator: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPPYLpOracle extends BaseContract {
  connect(runner?: ContractRunner | null): IPPYLpOracle;
  waitForDeployment(): Promise<this>;

  interface: IPPYLpOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getLpToAssetRate: TypedContractMethod<
    [market: AddressLike, duration: BigNumberish],
    [bigint],
    "view"
  >;

  getLpToSyRate: TypedContractMethod<
    [market: AddressLike, duration: BigNumberish],
    [bigint],
    "view"
  >;

  getOracleState: TypedContractMethod<
    [market: AddressLike, duration: BigNumberish],
    [
      [boolean, bigint, boolean] & {
        increaseCardinalityRequired: boolean;
        cardinalityRequired: bigint;
        oldestObservationSatisfied: boolean;
      }
    ],
    "view"
  >;

  getPtToAssetRate: TypedContractMethod<
    [market: AddressLike, duration: BigNumberish],
    [bigint],
    "view"
  >;

  getPtToSyRate: TypedContractMethod<
    [market: AddressLike, duration: BigNumberish],
    [bigint],
    "view"
  >;

  getYtToAssetRate: TypedContractMethod<
    [market: AddressLike, duration: BigNumberish],
    [bigint],
    "view"
  >;

  getYtToSyRate: TypedContractMethod<
    [market: AddressLike, duration: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getLpToAssetRate"
  ): TypedContractMethod<
    [market: AddressLike, duration: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLpToSyRate"
  ): TypedContractMethod<
    [market: AddressLike, duration: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOracleState"
  ): TypedContractMethod<
    [market: AddressLike, duration: BigNumberish],
    [
      [boolean, bigint, boolean] & {
        increaseCardinalityRequired: boolean;
        cardinalityRequired: bigint;
        oldestObservationSatisfied: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPtToAssetRate"
  ): TypedContractMethod<
    [market: AddressLike, duration: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPtToSyRate"
  ): TypedContractMethod<
    [market: AddressLike, duration: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getYtToAssetRate"
  ): TypedContractMethod<
    [market: AddressLike, duration: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getYtToSyRate"
  ): TypedContractMethod<
    [market: AddressLike, duration: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "SetBlockCycleNumerator"
  ): TypedContractEvent<
    SetBlockCycleNumeratorEvent.InputTuple,
    SetBlockCycleNumeratorEvent.OutputTuple,
    SetBlockCycleNumeratorEvent.OutputObject
  >;

  filters: {
    "SetBlockCycleNumerator(uint16)": TypedContractEvent<
      SetBlockCycleNumeratorEvent.InputTuple,
      SetBlockCycleNumeratorEvent.OutputTuple,
      SetBlockCycleNumeratorEvent.OutputObject
    >;
    SetBlockCycleNumerator: TypedContractEvent<
      SetBlockCycleNumeratorEvent.InputTuple,
      SetBlockCycleNumeratorEvent.OutputTuple,
      SetBlockCycleNumeratorEvent.OutputObject
    >;
  };
}
